/*
 * generated by Xtext 2.14.0
 */
package org.xtext.eal


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class OrionStandaloneSetup extends OrionStandaloneSetupGenerated {

	def static void doSetup() {
		new OrionStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
