/*
 * generated by Xtext 2.14.0
 */
package org.xtext.eal.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.eal.OrionRuntimeModule
import org.xtext.eal.OrionStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class OrionIdeSetup extends OrionStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new OrionRuntimeModule, new OrionIdeModule))
	}
	
}
